### PR TITLE
feat: Enable the browser agent to run in extension background contexts

### PR DESCRIPTION
**Pull request by jspivack**
Use fetch for sending harvest payloads when XMLHttpRequest is unavailable, such as in browser extension contexts
---

### Overview
The browser agent library currently is able to function in web worker contexts but fails specifically in browser extension contexts where XmlHttpRequest is unavailable. This PR enables automatically switching to sending metric events via fetch as a fallback.

### Testing

Tests likely needed for CI/CD

### CODE REVIEW

**Comment by jspivack** [comment]
Apologies for the messy diff, not sure what happened with my repo's fork syncing here

**Comment by cwli24** [comment]
> Apologies for the messy diff, not sure what happened with my repo's fork syncing here

Do you mind doing a merge and/or rebase?

**Comment by jspivack** [comment]
There we go. Much cleaner

**Comment by metal-messiah** [comment]
TYSM @jspivack , Thanks for raising this PR. I was glad to see it come through after earlier conversations interally. I'll run this through our testing suite.  In the meantime, can you work on signing the CLA and we can work on getting this passing and merged :)

**Comment by metal-messiah** [comment]
Unit testing - https://github.com/newrelic/newrelic-browser-agent/actions/runs/11166232441/job/31039750118

**Comment by metal-messiah** [comment]
Integration and E2E testing - https://github.com/newrelic/newrelic-browser-agent/actions/runs/11166221876

**Comment by metal-messiah** [comment]
All tests are passing, just waiting on CLA.  Thanks for contributing this!

**Review by metal-messiah — DISMISSED** [review]

**Comment by jspivack** [comment]
Great! Just waiting on CLA review from on our end

**Comment by jspivack** [comment]
I'm not sure what happened with the email / lack of email address on some of the commits but it should all be associated with my username. Can I sign the CLA on behalf of all commits?

**Comment by metal-messiah** [comment]
@jspivack Yeah give that a try, not sure what went wrong there

**Comment by JustinRush-NR** [comment]
@jspivack Can you retry the [signing link](https://cla-assistant.io/newrelic/newrelic-browser-agent?pullRequest=1206) again?

**Comment by jspivack** [comment]
Apologies for the delay, I'm still waiting for legal approval on the CLA from our side. Do you know if there might be any standard/ open source CLAs that this repo is able to accept instead?

**Pull request merged**
