### PR TITLE
chore: add jest tests for mapOwn

### PR DESCRIPTION
**Pull request by patrickhousley**
### Overview

Converting the jil browser tests for the `mapOwn` utility method to jest. Also updating the utility method to be more concise and use ES5 Object.entries native functionality.

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-7850

### CODE REVIEW

**Comment by cwli24** [comment]
Even though it'd be slightly more work, wouldn't it be ultimately cleaner to just re-eval the places using mapOwn and switch them over? I notice not all the usage is the same (sometimes can be done with `.keys()` or `.values()` and others `.entries()`, or can just be replaced with a `forEach`.

**Comment by patrickhousley** [comment]
> Even though it'd be slightly more work, wouldn't it be ultimately cleaner to just re-eval the places using mapOwn and switch them over? I notice not all the usage is the same (sometimes can be done with `.keys()` or `.values()` and others `.entries()`, or can just be replaced with a `forEach`.
> 
> I can volunteer to do this if you'd like to hand it off.

Sure @cwli24 if you would like to do that or I could.

**Review by metal-messiah — APPROVED** [review]

**Comment by patrickhousley** [comment]
> Even though it'd be slightly more work, wouldn't it be ultimately cleaner to just re-eval the places using mapOwn and switch them over? I notice not all the usage is the same (sometimes can be done with `.keys()` or `.values()` and others `.entries()`, or can just be replaced with a `forEach`.
> 
> I can volunteer to do this if you'd like to hand it off.

I opened a ticket to track this as a separate effort: https://issues.newrelic.com/browse/NEWRELIC-7937

**Comment by cwli24** [comment]
> > Even though it'd be slightly more work, wouldn't it be ultimately cleaner to just re-eval the places using mapOwn and switch them over? I notice not all the usage is the same (sometimes can be done with `.keys()` or `.values()` and others `.entries()`, or can just be replaced with a `forEach`.
> > I can volunteer to do this if you'd like to hand it off.
> 
> I opened a ticket to track this as a separate effort: https://issues.newrelic.com/browse/NEWRELIC-7937

Given that, can we just close this? Since this also changes `mapOwn` implementation

**Comment by patrickhousley** [comment]
No, this still has tests that have already been wrote and can be useful until that ticket is addressed.

**Review by bjfield — APPROVED** [review]

**Pull request merged**
