### PR TITLE
fix: npm package version reporting

### PR DESCRIPTION
**Pull request by patrickhousley**
### Overview

Fixing the version reported by the agent when using the npm package. The version the NPM package reports on BAM calls should match the version that is reported by other installation methods.

### Related Issue(s)

https://issues.newrelic.com/browse/NEWRELIC-8150

### Testing

Run the full build and use the local test server to verify the version on the BAM calls.

### CODE REVIEW

**Review by bjfield — APPROVED** [review]
Verified version in RUM calls for both NPM and regular builds when set via VERSION file or VERSION_OVERRIDE. VERSION_OVERRIDE supersedes VERSION file.

**Comment by cwli24** [comment]
Is the _env.js_ file useless/unused then?

**Comment by patrickhousley** [comment]
No, the `env.js` file is the default. If a consumer of the NPM package imports from the agent `src` directory, that is the constants they will get.

**Comment by patrickhousley** [comment]
No. We cant import node globals in `env.js`. It will break the customer's app.

**Comment by cwli24** [comment]
> No. We cant import node globals in `env.js`. It will break the customer's app.

But if they import from src then, wouldn't they face the same issue? If so, is that just unavoidable?

**Comment by patrickhousley** [comment]
Correct. We cannot fix this issue for customers that import from the `src` directory. They will have to wait until we sync the version numbers.

**Review by cwli24 — APPROVED** [review]

**Pull request merged**
